from marketmoodring.regime_detection.base import RegimeDetectionError
from marketmoodring.regime_detection.hidden_markov import HiddenMarkovRegimeDetection
from marketmoodring.regime_detection.wasserstein_kmeans import WassersteinKMeansRegimeDetection
